git:
    submodules: false

language: cpp

compiler:
    - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y g++ gcc gfortran ghostscript m4 make patch pkg-config wget python unzip libopenblas-dev liblapack-dev libhdf5-dev libscotch-dev libfftw3-dev libarpack2-dev libsuitesparse-dev libmumps-seq-dev libnlopt-dev coinor-libipopt-dev libgmm++-dev libtet1.5-dev gnuplot-qt autoconf automake autotools-dev bison flex gdb valgrind git cmake libopenmpi-dev

script:
    - autoreconf -i && ./configure --enable-download --enable-optim && ./3rdparty/getall -a
    - make
    - make check

install:
    - sudo make install

addons:
  coverity_scan:
    project:
        name: FreeFem/FreeFem-sources
        description: FreeFem
    build_command_prepend: autoreconf -i && ./configure --enable-download --enable-optim && ./3rdparty/getall -a
    build_command: make
    branch_pattern: develop
